[workspace]
resolver = "2"
members = [
  "packages/*",
  "contracts/factory",
  "contracts/pair",
  "contracts/pair_stable",
  "contracts/pair_concentrated",
  "contracts/pool_manager",
#  "contracts/pair_concentrated_inj", TODO: rewrite OB liquidity deployment
  "contracts/pair_astro_xastro",
  "contracts/router",
  "contracts/token",
  "contracts/whitelist",
  "contracts/cw20_ics20",
  "templates/*",
  "contracts/tokenomics/*",
  "contracts/periphery/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[patch.'https://github.com/astroport-fi/astroport-core']
astroport = { path = "packages/astroport" }

[patch.crates-io]
cw-multi-test = { git = "https://github.com/astroport-fi/cw-multi-test.git", rev = "269a2c829d1ad25d67caa4600f72d2a21fb8fdeb" }
